export { TabsPage } from './tabs/tabs';
export { PerfilPage } from "./perfil/perfil";
export { FitPage } from "./fit/fit";
export { RecomendacionPage } from "./recomendacion/recomendacion";
export { AgregarAlimentoPage } from "./agregar-alimento/agregar-alimento";
export { AgregarEjercicioPage } from "./agregar-ejercicio/agregar-ejercicio";
export { LoginPage } from "./login/login";
export { RegistrarPage } from "./registrar/registrar";
export { IngredientesPage } from "./ingredientes/ingredientes";